### ISSUE TITLE
Do you really need global and local sym links for Instant Client?

### ISSUE THREAD

**Issue by cjbj** [gilcrest/OracleMacOSXElCapitanSetup4Node#1]
For normal day-to-day development, I only ever create the Instant Client sym links in ~/lib.  I never sudo and don't create links in /usr/local/lib/  This makes installation a bit easier.

Thanks for pulling together all the steps!

**Comment by gilcrest** [comment]
I honestly don't know, actually - based on the "first installation option" on the [node-oracledb OS X guide](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#-531-install-instant-client-in-opt), it has you using sudo.  I assumed the first option in the guide would be the preferred one...  I didn't even read the second option as I saw the word alternative and figured why not go for the gusto.  I can see that was probably not the right way to go?  Also, in that same installation option are the instructions to add the links in /usr/local/lib/...  Maybe I should try the second installation option in the guide and retool my one pager here?  Sounds like that is really the least risky path as you don't need to sudo - right?

**Comment by cjbj** [comment]
I will swap the order of those install options.  If you are the sole user of the machine the non-root install should be fine.

**Comment by gilcrest** [comment]
Thanks, Chris - this makes a lot of sense...  I will redo install based on the non-root option and update my doc as well accordingly...
